doctrine_migrations:
    migrations_paths:
        'DoctrineMigrations': '%kernel.project_dir%/migrations'
    storage:
        table_storage:
            table_name: migration_versions  # Nom de la table où sont stockées les informations des migrations
    enable_profiler: false
